%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-mrpt-pf-localization
Version:        2.2.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mrpt_pf_localization package

License:        BSD
URL:            https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_pf_localization
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-ament-cmake-lint-cmake
Requires:       ros-iron-ament-cmake-xmllint
Requires:       ros-iron-ament-lint-auto
Requires:       ros-iron-mola-relocalization
Requires:       ros-iron-mp2p-icp
Requires:       ros-iron-mrpt-libgui
Requires:       ros-iron-mrpt-libros-bridge
Requires:       ros-iron-mrpt-libslam
Requires:       ros-iron-mrpt-msgs
Requires:       ros-iron-mrpt-msgs-bridge
Requires:       ros-iron-nav-msgs
Requires:       ros-iron-pose-cov-ops
Requires:       ros-iron-rclcpp
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-tf2
Requires:       ros-iron-tf2-geometry-msgs
Requires:       ros-iron-ros-workspace
BuildRequires:  cmake3
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-cmake-lint-cmake
BuildRequires:  ros-iron-ament-cmake-xmllint
BuildRequires:  ros-iron-ament-lint-auto
BuildRequires:  ros-iron-mola-relocalization
BuildRequires:  ros-iron-mp2p-icp
BuildRequires:  ros-iron-mrpt-libgui
BuildRequires:  ros-iron-mrpt-libros-bridge
BuildRequires:  ros-iron-mrpt-libslam
BuildRequires:  ros-iron-mrpt-msgs
BuildRequires:  ros-iron-mrpt-msgs-bridge
BuildRequires:  ros-iron-nav-msgs
BuildRequires:  ros-iron-pose-cov-ops
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-tf2
BuildRequires:  ros-iron-tf2-geometry-msgs
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-iron-mrpt-tutorials
%endif

%description
Package for robot 2D self-localization using dynamic or static (MRPT or ROS)
maps. The interface is similar to amcl (https://wiki.ros.org/amcl) but supports
different particle-filter algorithms, several grid maps at different heights,
range-only localization, etc.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Sat Oct 12 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.2.1-1
- Autogenerated by Bloom

* Wed Sep 25 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.2.0-1
- Autogenerated by Bloom

* Wed Sep 25 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.1.1-2
- Autogenerated by Bloom

* Mon Sep 02 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.1.1-1
- Autogenerated by Bloom

* Thu Aug 08 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.1.0-1
- Autogenerated by Bloom

* Tue May 28 2024 Markus Bader <markus.bader@tuwien.ac.at> - 2.0.0-1
- Autogenerated by Bloom

