%YAML 1.2
---
# It is safe to use coarse lattice values, since a post-processing path
# refining stage will normally improve the result, with a very reduced overall
# time cost:
grid_resolution_xy: 0.20    # [meters]
grid_resolution_yaw: 10.0   # [deg]

# find_feasible_paths_to_neighbors() params:
# Note: path refining will always use *all* PTG trajectories, despite this value
max_ptg_trajectories_to_explore: 51
max_ptg_speeds_to_explore: 1
ptg_sample_timestamps: [1.0, 2.0]  # seconds

# Weight of heading towards the target: 
# the larger, the most favorable to move "looking at" the target direction.
heuristic_heading_weight: 0.25

SE2_metricAngleWeight: 2.0
pathInterpolatedSegments: 3

maximumComputationTime: 10.0  # [seconds]

#saveDebugVisualizationDecimation: 1
debugVisualizationShowEdgeCosts: true
